import { Sparkles } from "lucide-react";

export default function Footer() {
  return (
    <footer className="border-t border-white/10 bg-gray-950/50 py-8">
      <div className="max-w-7xl mx-auto px-4 flex items-center justify-between text-sm text-gray-500">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-purple-500" />
          <span>AI Commerce — Simulated AI Shopping Assistant</span>
        </div>
        <span>All recommendations are generated by heuristic algorithms</span>
      </div>
    </footer>
  );
}
